version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - .:/srv
    environment:
      VIRTUAL_HOST: labinteractives.docker
    command: ["/bin/bash", "-l", "-c", "/usr/local/bin/supervisord -c /srv/config/supervisord.conf -j /tmp/supervisord.pid"]
